function buildHelpMessage(prefix = "!") {
    return [
        "📘 HƯỚNG DẪN LỆNH DHA BOT",
        "",
        "ℹ️ Lưu ý chung:",
        "- Các chế độ `on/off` (`hello`, `kick`) áp dụng theo từng nhóm hiện tại.",
        "- Các lệnh cần tag: `checktt`, `thongtin`, `kick`, `mute`, `unmute`, `addbqt`.",
        "- Mặc định chỉ chủ nhóm/phó nhóm được dùng lệnh.",
        "- Muốn cấp thêm người dùng lệnh: `addbqt @tag`.",
        "- Người không được phép dùng lệnh sẽ bị cảnh báo, đủ 5 lần sẽ bị kick.",
        "",
        "==============================",
        "1) NHÓM CHÀO MỪNG",
        "==============================",
        `- \`${prefix}hello\``,
        "  Xem trạng thái chào mừng thành viên mới trong nhóm.",
        `- \`${prefix}hello on\``,
        "  Bật gửi ảnh chào mừng khi có thành viên mới vào.",
        `- \`${prefix}hello off\``,
        "  Tắt ảnh chào mừng.",
        "",
        "==============================",
        "2) NHÓM KICK / RỜI NHÓM",
        "==============================",
        `- \`${prefix}kick\``,
        "  Xem trạng thái thông báo rời nhóm / bị kick.",
        `- \`${prefix}kick on\``,
        "  Bật thông báo rời nhóm / bị kick trong nhóm.",
        `- \`${prefix}kick off\``,
        "  Tắt thông báo rời nhóm / bị kick.",
        `- \`${prefix}kick @TenNguoiDung\``,
        "  Kick người được tag ra khỏi nhóm (khi bot có quyền).",
        `- \`${prefix}autokick\``,
        "  Xem trạng thái auto kick người từng bị kick.",
        `- \`${prefix}autokick on/off\``,
        "  Bật/tắt tự động kick khi người từng bị kick vào lại nhóm.",
        `- \`${prefix}autokicklist\``,
        "  Xem danh sách người đang nằm trong auto kick (tên + UID).",
        `- \`${prefix}autokickremove <uid>\``,
        "  Gỡ 1 UID ra khỏi danh sách auto kick.",
        `- \`${prefix}goautokick <uid>\``,
        "  Alias của lệnh autokickremove.",
        "",
        "==============================",
        "3) NHÓM KIỂM SOÁT CHAT",
        "==============================",
        `- \`${prefix}mute @TenNguoiDung\``,
        "  Mute người được tag: hễ nhắn là bot xoá tin ngay.",
        `- \`${prefix}unmute @TenNguoiDung\``,
        "  Gỡ mute người được tag.",
        `- \`${prefix}camnoibay\``,
        "  Xem trạng thái auto mute theo danh sách từ cấm.",
        `- \`${prefix}camnoibay on\``,
        "  Bật auto mute: dùng từ cấm là bot xoá tin + khoá mõm tự động.",
        `- \`${prefix}camnoibay off\``,
        "  Tắt auto mute theo từ cấm.",
        "  Danh sách từ cấm sửa trong file `src/config/bannedWords.txt` (mỗi dòng 1 từ/cụm từ).",
        "",
        "==============================",
        "4) NHÓM PHÂN QUYỀN LỆNH",
        "==============================",
        `- \`${prefix}addbqt @TenNguoiDung\``,
        "  (Admin) Thêm nhanh người được tag vào danh sách được dùng bot.",
        "",
        "==============================",
        "5) NHÓM THỐNG KÊ CHAT",
        "==============================",
        `- \`${prefix}xhchat\``,
        "  Top chat theo ngày (reset 0h Việt Nam, 10 người / 1 ảnh).",
        `- \`${prefix}xhchatthang\``,
        "  Top chat theo tháng hiện tại.",
        `- \`${prefix}xhchattong\``,
        "  Top chat tổng tích lũy toàn thời gian.",
        `- \`${prefix}rschat\``,
        "  Reset điểm chat hiện tại (`msgCount`) về 0 cho cả nhóm.",
        "  Không ảnh hưởng tổng tích lũy (`totalMsgCount`).",
        "",
        "==============================",
        "6) NHÓM TRA CỨU THÀNH VIÊN",
        "==============================",
        `- \`${prefix}checktt @TenNguoiDung\``,
        "  Xem card thống kê: tên, avatar, thời gian vào,",
        "  người thêm/duyệt, tổng tin nhắn tích lũy.",
        `- \`${prefix}thongtin @TenNguoiDung\``,
        "  Xem card thông tin profile cơ bản của người được tag.",
        "",
        "==============================",
        "7) TRỢ GIÚP",
        "==============================",
        `- \`${prefix}help\``,
        "  Mở lại bảng hướng dẫn này.",
    ].join("\n");
}

async function handleHelpCommand(api, message, threadId, prefix = "!") {
    const msg = buildHelpMessage(prefix);
    await api.sendMessage({ msg }, threadId, message.type);
}

module.exports = {
    handleHelpCommand,
};
